{{- if or (include "datapond.addonOn" (dict "root" $ "component" "trino")) (include "datapond.addonOn" (dict "root" $ "component" "polaris")) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iceberg-warehouse-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: iceberg
    component: warehouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.trino.persistence.size | default "50Gi" }}
  {{- if .Values.global.storageClass }}
  {{- include "datapond.storageClassName" (dict "value" .Values.global.storageClass "indent" 2) }}
  {{- end }}
{{- end }}
