{{- if and .Values.litellm.enabled .Values.litellm.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.litellm.serviceAccount.name | default "litellm" }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.litellm.name }}
  {{- with .Values.litellm.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . | quote }}
  {{- end }}
{{- end }}
